// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp_cTdQZuhyRzb1DpJFOxVZQPnmJUb15E',
    appId: '1:980763902668:web:302581543f7b56f88b3869',
    messagingSenderId: '980763902668',
    projectId: 'courseapp-8b9da',
    authDomain: 'courseapp-8b9da.firebaseapp.com',
    storageBucket: 'courseapp-8b9da.appspot.com',
    measurementId: 'G-6RYB87PES0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLG8Vog_k9E_HnBBMFxus9w0E_okLxQes',
    appId: '1:980763902668:android:cf171cfc016cb8518b3869',
    messagingSenderId: '980763902668',
    projectId: 'courseapp-8b9da',
    storageBucket: 'courseapp-8b9da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzkhgKIXiBsTMOypAhcMtl2PLFH7MjPyo',
    appId: '1:980763902668:ios:6740593f6722f9378b3869',
    messagingSenderId: '980763902668',
    projectId: 'courseapp-8b9da',
    storageBucket: 'courseapp-8b9da.appspot.com',
    iosBundleId: 'com.example.courseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzkhgKIXiBsTMOypAhcMtl2PLFH7MjPyo',
    appId: '1:980763902668:ios:6740593f6722f9378b3869',
    messagingSenderId: '980763902668',
    projectId: 'courseapp-8b9da',
    storageBucket: 'courseapp-8b9da.appspot.com',
    iosBundleId: 'com.example.courseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp_cTdQZuhyRzb1DpJFOxVZQPnmJUb15E',
    appId: '1:980763902668:web:2df49ed2024d08e98b3869',
    messagingSenderId: '980763902668',
    projectId: 'courseapp-8b9da',
    authDomain: 'courseapp-8b9da.firebaseapp.com',
    storageBucket: 'courseapp-8b9da.appspot.com',
    measurementId: 'G-NYN045GKW2',
  );
}
